[package]
name = "dock"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
ash = "0.38.0"
thiserror = "2.0.18"
wayland-backend = { version = "0.3.15", features = ["client_system"] }
wayland-client = "0.31.14"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[build-dependencies]
anyhow = "1.0.102"
bytemuck = "1.25.0"
naga = { version = "29.0.3", features = ["wgsl-in", "spv-out"] }
